# SPDX-FileCopyrightText: 2024 Alexandre Jesus <me@adbjesus.com>
#
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.2
    hooks:
    - id: reuse
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
    - id: markdownlint
